import { Entity } from '../entities/store'

export type Store<T extends Entity> = {
  getById: (id: string) => Promise<T | undefined> // return undefined if ID not found or server error
  getAll: () => Promise<T[] | undefined> // return undefined if server error
  create: (entity: T) => Promise<T | undefined> // return undefined if server error, return entity with id if success. Entity can be posted with id (it will be retained) or without id (it will be generated by the store)
  deleteById: (id: string) => Promise<T | undefined> // return undefined if ID not found or if server error
  update: (partialEntity: Partial<T>) => Promise<T | undefined> // return undefined if ID not found or server error
}
